-- CreateTable
CREATE TABLE "ASTEROID_FAVORITES" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "asteroid_id" TEXT NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateIndex
CREATE INDEX "ASTEROID_FAVORITES_asteroid_id_idx" ON "ASTEROID_FAVORITES"("asteroid_id");
