version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      challenge_network:
        aliases:
          - backend_alias

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      challenge_network:
        aliases:
          - frontend_alias

networks:
  challenge_network:
    driver: bridge
